### ISSUE TITLE
strip_tags panic

### ISSUE THREAD

**Issue by gembin** [e1r0nd/voca_rs#18]
```rust
let s = voca_rs::strip::strip_tags("<span style=\"color: rgb(51, 51, 51); font-family: \" microsoft=\"\" yahei=\"\" stheiti=\"\" wenquanyi=\"\" micro=\"\" hei=\"\" simsun=\"\" sans-serif=\"\" font-size:=\"\" 16px=\"\">】มีมี่’ เด็กสาวที่นอนไม่ค่อยหลับเนื่องจากกลัวผี ขี้เหงา และอะไรหลายๆ อย่างทำให้เธอมึนได้โล่เพราะไม่ค่อยได้นอน การที่เธอ นอนไม่หลับทำให้เธอได้เจอกับ ‘ดีเจไททัน’ แห่งคลื่น 99.99 MHzเขาจัดรายการในช่วง Midnight Fantasy ตีสามถึงตีห้า และมีมี่ก็เป็นผู้ฟังเพียงคนเดียวของเขาจากที่ตอนแรกเธอฟังดีเจไททันเพื่อช่วยปลอบประโลมการที่เธอต้องมาอยู่หอเพียงลำพัง แต่ไปๆ มาๆกลับกลายเป็นว่าเธออยู่รอฟังเขาทุกคืนทำให้เธอไปเรียนแบบมึนๆ จนบังเอิญไปนอนหลับซบ ‘ธรรม’ผู้ชายจอมกวนที่บังเอิญมานอนให้เธอซบ! จนอาจารย์สั่งให้ไปทำรายงานคู่กัน และนั่นก็เป็นที่มาของการที่เธอเริ่มไม่แน่ใจแล้วว่าเธอปลื้มดีเจไททัน หรือแอบหวั่นไหวกับนายจอมกวนคนนี้กันแน่</span><br />");
println!("{}",s);
```
Got panic:
```
thread 'main' panicked at 'index 779 out of range for slice of length 664', src/libcore/slice/mod.rs:2674:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2674
  14: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2838
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2656
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1883
  17: voca_rs::strip::unicode_string_range
             at /Users/gembin/.cargo/registry/src/github.com-1ecc6299db9ec823/voca_rs-1.10.0/src/strip.rs:68
  18: voca_rs::strip::strip_html_tags
             at /Users/gembin/.cargo/registry/src/github.com-1ecc6299db9ec823/voca_rs-1.10.0/src/strip.rs:87
  19: voca_rs::strip::strip_tags
             at /Users/gembin/.cargo/registry/src/github.com-1ecc6299db9ec823/voca_rs-1.10.0/src/strip.rs:55
```

**Comment by gembin** [comment]
Any solutions to fix this bug?

**Comment by e1r0nd** [comment]
@gembin Please review the following commit https://github.com/e1r0nd/voca_rs/commit/4a5070164f51235704ce870508067fe90883c024 and close this issue if it works for you or provide additional test cases if it doesn't.

**Comment by gembin** [comment]
Awesome! It works.
